package ru.stqa.pft.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ru.stqa.pft.model.ContactData;

import java.util.List;

public class ContactDeletionTests extends TestBase {

  @BeforeMethod
  public void ensurePreConditions() {
    app.goTo().gotoHome();
    //if (!app.contact().isThereAContact()) {
    if (app.contact().list().size()==0) {
      app.contact().create(new ContactData("Ivana", "Ivanova", "iva@tut.by", "newgroup777"));
    }
  }

  @Test
  public void testContactDeletion() {
    List<ContactData> before = app.contact().list();
    app.contact().delete(1);
    List<ContactData> after = app.contact().list();
    Assert.assertEquals(after.size(), before.size()-1); // проверка что записей стало меньше на 1
    before.remove(1); // удаляем из списка before ту же запись что и тестом
    Assert.assertEquals(before, after);
    //app.getSessionHelper().logout(); // разлогин
  }


}
