package ru.stqa.pft.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class ContactDeletionTests extends TestBase {

  @Test
  public void testContactDeletion() {
    app.getNavigationHelper().gotoHome();
    app.getContactHelper().selectContact();
    app.getContactHelper().deleteSelectedGroups();
    //assertThat(driver.switchTo().alert().getText(), is("Delete 1 addresses?"));
    app.getContactHelper().closeAlert();
    app.getNavigationHelper().gotoHome();
  }

}
