package ru.stqa.pft.tests;// Generated by Selenium IDE

import org.hamcrest.CoreMatchers;
import org.hamcrest.MatcherAssert;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ru.stqa.pft.model.ContactData;
import ru.stqa.pft.model.Contacts;

import java.util.List;
import java.util.Set;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;

public class ContactDeletionTests extends TestBase {

  @BeforeMethod
  public void ensurePreConditions() {
    app.goTo().gotoHome();
    //if (!app.contact().isThereAContact()) {
    if (app.contact().list().size()==0) {
      app.contact().create(new ContactData().withFirstname("Ivana").withLastname("Ivanova").withEmail("iva@tut.by").withGroup("newgroup777"));
    }
  }

  @Test
  public void testContactDeletion() {
    Contacts before = app.contact().all();
    ContactData deletedContact = before.iterator().next();
    app.contact().delete(deletedContact);
    Contacts after = app.contact().all();
    Assert.assertEquals(after.size(), before.size()-1); // проверка что записей стало меньше на 1

    //before.remove(deletedContact); // удаляем из списка before ту же запись что и тестом
    assertThat(after, equalTo(before.without(deletedContact)));
    //Assert.assertEquals(before, after);
    //app.getSessionHelper().logout(); // разлогин
  }


}
