package ru.stqa.pft.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ru.stqa.pft.appmanager.SessionHelper;
import ru.stqa.pft.model.GroupData;

public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDeletion() {
    app.getNavigationHelper().gotoGroupPage();
    // проверка количества групп до ввода новой
    int before = app.getGroupHelper().getGroupCount();
    if (! app.getGroupHelper().isThereAGroup()) {
      app.getGroupHelper().createGroup(new GroupData("test1", "header1", "footer1"));
    }
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getNavigationHelper().gotoGroupPage();

    // проверка количества групп после ввода новой
    int after = app.getGroupHelper().getGroupCount();
    Assert.assertEquals(after, before-1);

    app.getNavigationHelper().gotoHome();
    app.getSessionHelper().logout();
  }

}
