package ru.stqa.pft.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ru.stqa.pft.appmanager.SessionHelper;
import ru.stqa.pft.model.GroupData;

import java.util.List;

public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDeletion() {
    app.getNavigationHelper().gotoGroupPage(); // на страницу групп
    if (! app.getGroupHelper().isThereAGroup()) { //проверка есть ли группы, если нет - создание
      app.getGroupHelper().createGroup(new GroupData("test1", "header1", "footer1"));
    }
    //int before = app.getGroupHelper().getGroupCount(); // проверка количества групп до удаления
    List<GroupData> before = app.getGroupHelper().getGroupList();
    app.getGroupHelper().selectGroup(before.size()-2);  // выбираем группу номер (по поряд. номеру) 3
    app.getGroupHelper().deleteSelectedGroups(); // удаляем
    app.getNavigationHelper().gotoGroupPage(); // на страницу групп
    //int after = app.getGroupHelper().getGroupCount(); // проверка количества групп после удаления
    List<GroupData> after = app.getGroupHelper().getGroupList();
    //Assert.assertEquals(after, before-1); // проверка что групп стало меньше на 1
    Assert.assertEquals(after.size(), before.size()-1);
    app.getNavigationHelper().gotoHome(); // на страницу хоум
    app.getSessionHelper().logout(); // разлогин
  }

}
