package ru.stqa.pft.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.pft.model.GroupData;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().initGroupCreation();
    app.getGroupHelper().fillGroupForm(new GroupData("newgroup111", "header111", "foottter111"));
    //app.getGroupHelper().fillGroupForm(new GroupData("newgroup111", null, null));
    app.getGroupHelper().submitGroupCreation();
    app.getNavigationHelper().gotoGroupPage();
    app.getNavigationHelper().gotoHome();
    app.getSessionHelper().logout();
  }

}
