package ru.stqa.pft.tests;// Generated by Selenium IDE

//import org.junit.After;
//import org.junit.Before;
//import org.junit.Test;

import org.testng.annotations.Test;
import ru.stqa.pft.model.GroupData;


public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    app.gotoGroupPage();
    app.initGroupCreation();
    app.fillGroupForm(new GroupData("newgroup1", "111", "ttt"));
    app.submitGroupCreation();
    app.gotoGroupPage();
    app.gotoHomePage();
    app.logout();
  }

}
