package ru.stqa.pft.addressbook;// Generated by Selenium IDE
//import org.junit.Test;

import org.junit.After;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.concurrent.TimeUnit;

//import org.junit.jupiter.api.Before;
//import org.junit.jupiter.api.After;
public class NewGroupCreationTest {
  FirefoxDriver driver;
  // private WebDriver driver;
  //private Map<String, Object> vars;
  //JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
    //js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  }
  @Test
  public void newGroupCreation() {
    driver.get("http://localhost/addressbook/group.php");
    driver.manage().window().setSize(new Dimension(777, 693));
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.name("pass")).click();
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    driver.findElement(By.linkText("groups")).click();
    driver.findElement(By.name("new")).click();
    driver.findElement(By.name("group_name")).click();
    driver.findElement(By.name("group_name")).sendKeys("test11");
    driver.findElement(By.name("group_header")).click();
    driver.findElement(By.name("group_header")).sendKeys("test22");
    driver.findElement(By.name("group_footer")).click();
    driver.findElement(By.name("group_footer")).sendKeys("test33");
    driver.findElement(By.name("submit")).click();
    driver.findElement(By.linkText("group page")).click();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
}
