package ru.stqa.pft;// Generated by Selenium IDE

//import org.junit.After;
//import org.junit.Before;
//import org.junit.Test;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.time.Duration;


public class NewGroupCreationTests {
  FirefoxDriver wd = new FirefoxDriver();

  @BeforeMethod
  public void setUp() throws Exception{
    wd.manage().timeouts().implicitlyWait(Duration.ofSeconds(60));
  }
  @Test
  public void NewGroupCreationTests() {
    wd.get("http://localhost/addressbook/");
    wd.manage().window().setSize(new Dimension(800, 640));
    wd.findElement(By.name("user")).click();
    wd.findElement(By.name("user")).sendKeys("admin");
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).sendKeys("secret");
    {
      WebElement element = wd.findElement(By.cssSelector("input:nth-child(7)"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = wd.findElement(By.cssSelector("input:nth-child(7)"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = wd.findElement(By.cssSelector("input:nth-child(7)"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).release().perform();
    }
    wd.findElement(By.cssSelector("input:nth-child(7)")).click();
    wd.findElement(By.linkText("groups")).click();
    wd.findElement(By.name("new")).click();
    {
      WebElement element = wd.findElement(By.name("group_name"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = wd.findElement(By.name("group_name"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = wd.findElement(By.name("group_name"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).release().perform();
    }
    wd.findElement(By.name("group_name")).click();
    wd.findElement(By.name("group_name")).sendKeys("newgroup1");
    wd.findElement(By.name("group_header")).click();
    wd.findElement(By.name("group_header")).sendKeys("111");
    wd.findElement(By.name("group_footer")).click();
    wd.findElement(By.name("group_footer")).sendKeys("ttt");
    {
      WebElement element = wd.findElement(By.cssSelector("form:nth-child(2)"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = wd.findElement(By.cssSelector("form:nth-child(2)"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = wd.findElement(By.cssSelector("form:nth-child(2)"));
      Actions builder = new Actions(wd);
      builder.moveToElement(element).release().perform();
    }
    wd.findElement(By.cssSelector("form:nth-child(2)")).click();
    wd.findElement(By.name("submit")).click();
    wd.findElement(By.linkText("groups")).click();
    wd.findElement(By.linkText("home")).click();
    wd.findElement(By.linkText("Logout")).click();
  }
  @AfterMethod
  public void tearDown() {
    wd.quit();
  }
}
